### ISSUE TITLE
Create a seperate output/input foler

### ISSUE THREAD

**Issue by MSvanTergouw** [course-dprep/The_impact_of_Airbnb_hosts_on_guest_reviews#72]
This is where the scraped URLs will come after running src. 1

**Comment by JulianPetersIsCoding** [comment]
Hey Marc,

Situation: We create output with our code. Hence we need to store this somewhere. At the moment it will assign a random location. We need to structure this, so that the code will be placed in a folder that we assigned for it.

Output: Output will be placed in the assigned folder. 

Solution example: Add a line of code to the makefile, so that it assigns the place of storage. 

Kind regards,

Julian Peters
